### ISSUE TITLE
Upgrade vcluster to latest version

### ISSUE THREAD

**Issue by tobru** [projectsyn/component-vcluster#18]
## Context

Upgrade vcluster to the [latest available version](https://github.com/loft-sh/vcluster/releases).
By the time of this issue got created, we're at `0.5.0-beta.0`, according to [defaults](https://github.com/projectsyn/component-vcluster/blob/master/class/defaults.yml#L17=). Also k3s is outdated.

Make sure that Renovate is able to keep the versions up-to-date.

## Alternatives

n/a

**Comment by bastjan** [comment]
Fixed by #27 #28 #29 #30 #31
